version: '3.8'

services:
  mariadb:
    image: "mariadb:latest"
#    network_mode: "bridge"
    container_name: "mariadb"
    restart: unless-stopped
    environment:
      # - MARIADB_MASTER_HOST=172.19.0.1
      MARIADB_ROOT_PASSWORD: 1111
      # - MARIADB_USER=strapi
      # - MARIADB_PASSWORD=strapi
      # - MARIADB_DATABASE=strapi
    ports:
      - "3306:3306"
  adminer:
    image: "adminer:latest"
    restart: always
    ports:
        - "8080:8080"
    environment:
        - ADMINER_DEFAULT_SERVER=mariadb
        - ADMINER_DESIGN=nette
    depends_on:
        - mariadb
